### ISSUE TITLE
getCollars only outputs brackets

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker#16]
in pythondialog branch...

python_dialogs/getCollars.py

Output for any reasonable input is:

``` sh
$ ./getCollars.py
{}
```

Output should be:

``` sh
$ ./getCollars.py
1: 172600000
2: 213000
```

for inputs of 172600000 and 213000.

**Comment by nanshu2011** [comment]
Bug fixed.

Now the output is:

$ ./getCollars.py 
{1: 172600000, 2: 213000} 

for inputs 172600000 and 213000.

and nothing for no inputs.

I made a dictionary to hold all the frequencies so that when it gets returned, it can be used later in other parts of the project as well as print in the terminal.
