### ISSUE TITLE
unistd.h on Windows

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker#22]
DNE.  Look at other option for doing getopt on windows.  I'm pretty sure there's an option.

**Comment by ntlhui** [comment]
The shared library is no longer dependent on unistd.h or getopt.h.  The python install should work now @SamuelLBau

**Comment by ntlhui** [comment]
Do we need command line capabilities for the fft_detect on Windows?  That is, do we ever have a use case for interacting with the fft_detect from the command line on Windows?

**Comment by SamuelLBau** [comment]
Here is the code my python currently uses to call fft_detect. As far as I can tell, I am creating  a command string as it would be typed from commandPrompt while in the radio_collar_tracker directory or one below. I do not know how subprocess calls fft_detect, so this may not be the answer your question.

GNU_RADIO_PIPELINE = programPath + '/fft_detect/fft_detect'
argString = '-f ' + str(beat_freq) + ' -i ' + str(raw_file) + ' -o ' + str(collarFile)
p = subprocess.call(GNU_RADIO_PIPELINE + ' ' + argString, shell=True)

I am not sure if this relates to your question.

**Comment by ntlhui** [comment]
Can you call the library directly?

**Comment by SamuelLBau** [comment]
I realized that most issues I was having were due to the version of visual studio compiler I was using. Will you have access to the computer you are installing this on? I am concerned that each potential compiler may require additional configurations.

In particular, VS 2008 requires a lot of configuring / finagling to make work properly.
